name: Build and Publish

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Adjust to your desired Python version

    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false
      shell: bash

    - name: Install project dependencies
      run: |
        poetry install
      shell: bash

    - name: Build Docker image
      run: |
        docker build -t aspadhi/python-build .
      shell: bash

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: aspadhi/python-build:latest
        push: true
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

