name: Build and Publish

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Adjust to your desired Python version

    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false
      shell: bash

    - name: Install project dependencies
      run: |
        poetry install
      shell: bash
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: aspadhi/python-build:latest

